apiVersion: v1
kind: Service
metadata:
  name: cloud-mosquitto-service
  labels:
    run: mosquitto
spec:
  type: NodePort
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
    nodePort: 30003
  selector:
    app: mosquitto
